### ISSUE TITLE
Follower configurations disappear when the webthing server is restarted

### ISSUE THREAD

**Issue by cgerhard** [flatsiedatsie/followers-addon#12]
I installed webthing 0.12 on an existing raspberry pi I had running other things, so did not use the image. It did not create a home directory for the webthing user, but appeared to work. I then upgraded to 1.0 and when I added follower configurations they worked until the webthing service was restarted, either on it's own or via a reboot.

Ticking the debug option in the followers config and now I saw this error in the log:

2021-01-03 10:40:30.520 INFO   : followers: Error: could not store data in persistent store: [Errno 2] No such file or directory: '/home/webthings/.webthings/data/followers/persistence.json'

creating the directory for that file and then adding a new follower resulted in the file appearing and now on restart the followers persist.

**Comment by flatsiedatsie** [comment]
Thanks. I've added some code to check if the directory exists. A future verson will have this change.
