### ISSUE TITLE
Can't delete a rule

### ISSUE THREAD

**Issue by madb1lly** [flatsiedatsie/followers-addon#3]
Hi @flatsiedatsie,

On Fenix and Fennec I can't delete any rules,  tapping the cross has no effect.

Cheers 🙂

**Comment by flatsiedatsie** [comment]
That's odd. Could you perhaps have a look at the debug output in the javascript console? (If I left any in..)

**Comment by madb1lly** [comment]
Hi @flatsiedatsie,
This is what I get in the console when I click the X:
`Uncaught TypeError: event.path is undefined
    regenerate_items [redacted]/extensions/followers/js/extension.js:169
extension.js:169:6
    regenerate_items [redacted]/extensions/followers/js/extension.js:169`

Cheers 🙂

**Comment by flatsiedatsie** [comment]
Thanks, that's very helpful.

**Comment by madb1lly** [comment]
Hi @flatsiedatsie,
Unfortunately that update didn't fix this problem. I also found I have the same problem on desktop. Here's the console log from when I click that button:
`Uncaught TypeError: event.path is undefined
    regenerate_items [redacted]/extensions/followers/js/extension.js:169
extension.js:169:6
    regenerate_items [redacted]/extensions/followers/js/extension.js:169`

**Comment by flatsiedatsie** [comment]
Strange. In the latest version that points to:

`	const final_delete_button = clone.querySelectorAll('.rule-delete-confirm-button')[0];`

Which should work (and works here).

So I suspect you haven't updated the addon?

**Comment by madb1lly** [comment]
Hi @flatsiedatsie,
It was showing 0.1.3 so i assumed it had updated.  I disabled and reenabled and now I can remove rules.
Cheers 🙂

**Comment by flatsiedatsie** [comment]
In that case you probably just had to refresh the page.
