### ISSUE TITLE
How to compare two properties

### ISSUE THREAD

**Issue by madb1lly** [flatsiedatsie/followers-addon#4]
Hi @flatsiedatsie,

In https://github.com/mozilla-iot/gateway/issues/805 you suggested that I could use this adapter to compare two properties but I'm struggling to understand how. To me it looks like this addon can only compare against constants.

Here's what I want to do:

If OutsideSensor.Temperature > InsideSensor.Temperature
Then send WebNotification

Where the sensor.temperature indicates thing.property.

Similarly for the opposite comparison.

So can I do that with Followers? If not then don't worry, it's not what you intended as the use, but if I can use it that will be great!

Cheers 🙂

**Comment by flatsiedatsie** [comment]
No, I suggested you could use the Rules functionality. This addon won't help you, but the Rules system can do this :-) Just add both properties on the left side of a new rule, and the thing you want to toggle on the right.

Actually, now that I think about it, I better understand your issue. If both properties are variables, then you cannot compare them, you are right.

**Comment by madb1lly** [comment]
Thanks for the clarification, I'm glad I'm not being dum 😃

**Comment by flatsiedatsie** [comment]
No, just me ;-)
