### ISSUE TITLE
Copy property of same type

### ISSUE THREAD

**Issue by rzr** [flatsiedatsie/followers-addon#7]
It should be easier to implements that the default scale feature.

it was discussed at:

https://github.com/mozilla-iot/gateway/issues/805#issuecomment-451242864

**Comment by flatsiedatsie** [comment]
Perhaps I misunderstand, but you seem to have removed functionality? Why would that be a good idea? Instead of just copying, the current implementation allows values to re reversed or scaled, which is a key component of why this addon is valueable.

**Comment by rzr** [comment]
yes this is not intended to be merged I wanted to share my use case and how I used your base to patch to achieve my goals,

Now may you suggest me a way to refactor your adapter to support this new feature

**Comment by flatsiedatsie** [comment]
Ah I see.

I'm not sure about your second sentence. The addon already supports that use case?

**Comment by rzr** [comment]
String copy is all I need for now
